# Site settings
title: Skrifa KB
site_title: Skrifa KB
description: Skrifa Documentation
url: "http://kb.skrifa.io" # the base hostname & protocol for your site
github_username: humeansacrifice
baseurl: /help/


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

# taxonomy stuff
category-list: [Formatting, Series, Getting Started, Search, Categories, Writing]
tag-list: [Technical Setup, Moss, Neil Young]



exclude: ["README.md", "article_template.md", "LICENSE"]
